import Header from '@/components/ui/header'
import { ThemeProvider } from '@/components/ui/theme-provider'
import clsx from 'clsx'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={clsx(
					`${inter.className} flex flex-col items-center justify-between max-w-[1290px] mx-auto p-3`,
				)}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<div>{children}</div>
				</ThemeProvider>
			</body>
		</html>
	)
}
