import Header from '@/components/ui/header'
import { ThemeProvider } from '@/components/ui/theme-provider'
import { Toaster } from '@/components/ui/toaster'
import clsx from 'clsx'
import type { Metadata } from 'next'
import { Cookie, Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import AppProvider from './app-provider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const cookieStores = cookies()
	const sessionToken = cookieStores.get('session')?.value
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={clsx(`${inter.className} max-w-[1290px] w-[1270px] mx-auto`)}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<AppProvider initialSessionToken={sessionToken}>
						{children}
					</AppProvider>
				</ThemeProvider>
				<Toaster />
			</body>
		</html>
	)
}
